### ISSUE TITLE
No Msvm_PlannedComputerSystem could be found with name "xxxxxx"

### ISSUE THREAD

**Issue by abhisek-mishra** [Microsoft/Windows-classic-samples#10]
Hi,
I am struggling with this code, it will be really helpful if you can help me.
I have created a vm on win 2016 server using Hyper Visor and taken a snapshot of my vm using Hyper Visor.

I then run your code by adding the command line arguments as ""ImportSnapshots" "test1" "C:\\bktest1\\test1\\Snapshots""

But when I debug I get the error as "No Msvm_PlannedComputerSystem could be found with name "test1"",
I tried importing the vm but that too fails.
On further debugging into the code I figured out the output of this query is null.
""SELECT * FROM Msvm_PlannedComputerSystem WHERE ElementName=\"test1\"""

I tried changing the query to "SELECT * FROM Msvm_PlannedComputerSystem", but the output of this 
query is also null.

Command Line also gives the same error :+1: 
C:\Samples\PVM\bin\Debug>PVMSamples.exe "ImportSnapshots" "test1" "E:\\bktest1\\test1\\Snapshots"

Unhandled Exception: System.Management.ManagementException: No Msvm_PlannedComputerSystem could be found with name "test1"
   at Microsoft.Samples.HyperV.Common.WmiUtilities.GetVmObject(String name, String className, ManagementScope scope) in c:\Samples\PVM\WmiUtilities.cs:line 286
   at Microsoft.Samples.HyperV.Common.WmiUtilities.GetPlannedVirtualMachine(String name, ManagementScope scope) in c:\Samples\PVM\WmiUtilities.cs:line 249
   at Microsoft.Samples.HyperV.PVM.ImportUtilities.ImportSnasphotDefinitions(String pvmName, String snapshotFolderPath) in c:\Samples\PVM\ImportUtilities.cs:line 117
   at Microsoft.Samples.HyperV.PVM.Program.Main(String[] args) in c:\Samples\PVM\Program.cs:line 78

Will it be possible for you to suggest where I am wrong, thanks a lot for your help and support.

**Comment by oldnewthing** [comment]
Is this still an issue?
